
name: Browser tests

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    standard-design:
        name: "Core browser tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            test-suite:  '--mode=standard --profile=core --suite=web --tags=~@broken'
        secrets:
            AUTOMATION_CLIENT_ID: ${{ secrets.AUTOMATION_CLIENT_ID }}
            AUTOMATION_CLIENT_INSTALLATION: ${{ secrets.AUTOMATION_CLIENT_INSTALLATION }}
            AUTOMATION_CLIENT_SECRET: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
